// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD57mYBQ2-FkJvFwGluT4R15_9t0CunzI4',
    appId: '1:144836741955:web:762591b358a2f6cbc2fdf6',
    messagingSenderId: '144836741955',
    projectId: 'inclass-15-project',
    authDomain: 'inclass-15-project.firebaseapp.com',
    storageBucket: 'inclass-15-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYYy56468yWTq3mXWvrsuaotGgi6By3vs',
    appId: '1:144836741955:android:6d0cd5d1f0e327eec2fdf6',
    messagingSenderId: '144836741955',
    projectId: 'inclass-15-project',
    storageBucket: 'inclass-15-project.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD57mYBQ2-FkJvFwGluT4R15_9t0CunzI4',
    appId: '1:144836741955:web:46594025e2db89d6c2fdf6',
    messagingSenderId: '144836741955',
    projectId: 'inclass-15-project',
    authDomain: 'inclass-15-project.firebaseapp.com',
    storageBucket: 'inclass-15-project.firebasestorage.app',
  );
}
